name: Terraform CI

on:
  push:
    branches:
      - feature/firstpipeline

permissions:
  contents: read
  id-token: write

jobs:

  terraform-ci-pipeline:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/prod

    steps:

      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: latest

      # 5. Initialize TFLint
      - name: Initialize TFLint
        run: tflint --init

      # 6. Run TFLint
      - name: Run TFLint
        run: tflint

      # 7. Checkov Security Scan
      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: environments/prod
          framework: terraform
          output_format: sarif
          skip_check: CKV2_AZURE_31
          log_level: WARNING

      # 8. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 9. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 10. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 11. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan